language: julia
os:
  - linux
julia:
  - 1.1
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly
before_install:
  - sudo apt-get install ruby bundler cmake pkg-config git libssl-dev
  - gem install --no-ri --no-rdoc licensee
  - gem install --no-ri --no-rdoc commonmarker
